package mx.com.juca.store.persistence.domain;

// Generated Feb 9, 2011 9:17:03 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductOrder generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_ORDERS")
public class ProductOrder implements java.io.Serializable {

	private static final long serialVersionUID = 707536768265498906L;
	private ProductOrderId id;
	private Product product;
	private Order order;
	private int numberItems;

	public ProductOrder() {
	}

	public ProductOrder(ProductOrderId id, Product product, Order order,
			int numberItems) {
		this.id = id;
		this.product = product;
		this.order = order;
		this.numberItems = numberItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idOrder", column = @Column(name = "id_order", nullable = false)) })
	public ProductOrderId getId() {
		return this.id;
	}

	public void setId(ProductOrderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "number_items", nullable = false)
	public int getNumberItems() {
		return this.numberItems;
	}

	public void setNumberItems(int numberItems) {
		this.numberItems = numberItems;
	}

	@Override
	public String toString() {
		return "ProductOrder [id=" + id + ", product=" + product + ", order="
				+ order + ", numberItems=" + numberItems + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductOrder other = (ProductOrder) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
