package mx.com.juca.store.persistence.domain;

// Generated Feb 9, 2011 9:17:03 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductOrderId generated by hbm2java
 */
@Embeddable
public class ProductOrderId implements java.io.Serializable {

	private static final long serialVersionUID = 7624455919320327761L;
	private int idProduct;
	private int idOrder;

	public ProductOrderId() {
	}

	public ProductOrderId(int idProduct, int idOrder) {
		this.idProduct = idProduct;
		this.idOrder = idOrder;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductOrderId))
			return false;
		ProductOrderId castOther = (ProductOrderId) other;

		return (this.getIdProduct() == castOther.getIdProduct())
				&& (this.getIdOrder() == castOther.getIdOrder());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdOrder();
		return result;
	}

	@Override
	public String toString() {
		return "ProductOrderId [idProduct=" + idProduct + ", idOrder="
				+ idOrder + "]";
	}

}
